version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: chatbot_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
