name: CI/CD Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Continuous Integration (Test + Build)
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        working-directory: ./backend
        run: |
          # Install package in development mode
          pip install -e .
          
          # Run tests with explicit path
          python -m pytest tests/ -v

      - name: Build Docker image
        run: docker build -t yourusername/fastfront:ci .

  # Continuous Deployment (Only runs on main branch)
  cd:
    needs: ci  # Depends on CI job succeeding
    if: github.ref == 'refs/heads/main'  # Only deploy from main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker build -t yourusername/fastfront:latest .
          docker push yourusername/fastfront:latest

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend